apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nokia-mongo
    namespace: nokia
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: nokia-mongo3
        spec:
            containers:
                - name: mongocontainer
                  image: mongo
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 27017
                        name: server
            nodeSelector:
                name: masternode
---

apiVersion: v1
kind: Service
metadata:
    name: nokia-mongo
    namespace: nokia
spec:
    ports:
        - name: http
          port: 27017
    selector:
        app: nokia-mongo3
