apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: nokia-mqtt
    namespace: nokia
spec: 
    replicas: 1
    template:
        metadata:
            labels:
                app: nokia-mqtt3
        spec:
            containers:
                - name: mosquittocontainer
                  image: mqtt-nokia
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 1883
                        name: server
            nodeSelector: 
                name: masternode
---

apiVersion: v1
kind: Service
metadata: 
    name: nokia-mqtt
    namespace: nokia
spec:
    ports:
        - name: http
          port: 1883
    selector: 
        app: nokia-mqtt3
